AWSTemplateFormatVersion: "2010-09-09"
Description: Code pipeline Stack for front end and back end.

Parameters:
  Environment:
    Type: String
  FrontendGitHubRepositoryName:
    Type: String
    Description: GitHub repository name for front end
  FrontendGitHubBranchName:
    Type: String
    Description: GitHub branch name for front end
  FrontendBucketName:
    Type: String
    Description: S3 bucket name for front end  
  CodeStarConnectionArn:
    Type: String
    Description: CodeStarConnectionArn
  FrontendCodeBucket:
    Type: String
    Description: S3 bucket name for front end code
  
Resources:
  FrontendCodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${FrontendBucketName}
                  - !Sub arn:aws:s3:::${FrontendBucketName}/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              - Effect: Allow
                Action:
                  - cloudfront:CreateInvalidation
                Resource:
                    - !Join ["", [ !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/", !ImportValue CloudFrontDistributionId]] 
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                Resource:
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/CLOUDFRONT_ID"
                  - !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/S3_BUCKET"

  FrontendCodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${FrontendBucketName}
                  - !Sub arn:aws:s3:::${FrontendBucketName}/*
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: "*"
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: !Sub "${CodeStarConnectionArn}"

  FrontendCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: FrontendDeploymentBuild
      Source:
        Type: S3
        Location: !Sub "${FrontendCodeBucket}/source.zip"
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/amazonlinux2-x86_64-standard:4.0"
        Type: LINUX_CONTAINER
      ServiceRole: !Ref FrontendCodeBuildServiceRole

  FrontendCodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: "Frontend-Code-Pipeline"
      RoleArn: !GetAtt FrontendCodePipelineServiceRole.Arn
      Stages:
        - Name: Source
          Actions:
            - Name: S3Source
              ActionTypeId:
                Category: "Source"
                Owner: "AWS"
                Provider: "S3"
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                S3Bucket: !Ref FrontendCodeBucket
                S3ObjectKey: "source.zip"
              RunOrder: 1

        - Name: BuildAndDeploy
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref FrontendCodeBuildProject
              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location: !Sub "${FrontendBucketName}"