template-file-path: templates/pipeline/backend-code-pipeline.yaml

parameters:
  Environment: dev
  BackendGitHubRepositoryName: manikandan-c-kf/test-mebweb-backend
  BackendGitHubBranchName: main
  CodeStarConnectionArn: arn:aws:codeconnections:us-east-1:961341513566:connection/cbd1908f-af4a-42bf-8464-9fc9e8ffc11d
  ECRRepositoryName: mebweb-ecr-repository