template-file-path: templates/pipeline/frontend-code-pipeline.yaml

parameters:
  Environment: dev
  FrontendGitHubRepositoryName: manikandan-c-kf/test-mebweb-frontend
  FrontendGitHubBranchName: main
  FrontendBucketName: mebwbfrontendbucket 
  CodeStarConnectionArn: arn:aws:codeconnections:us-east-1:961341513566:connection/cbd1908f-af4a-42bf-8464-9fc9e8ffc11d