template-file-path: templates/s3.yaml

parameters: 
  Environment: dev
  FrontendBucketName: mebwebfrontend 
  AccessLogsBucketName: mebwebaccesslogs
  BackendArtifactBucketName: mebwebbackendartifact 