template-file-path: templates/s3.yaml

parameters: 
  Environment: dev
  FrontendBucketName: frontendbucket 
  AccessLogsBucketName: accesslogsbucket
  BackendArtifactBucketName: backendartifactbucket 