template-file-path: templates/s3.yaml

parameters: 
  Environment: dev
  FrontendBucketName: mebwbfrontendbucket 
  AccessLogsBucketName: mebwbaccesslogsbucket
  BackendArtifactBucketName: mebwbbackendartifactbucket 