template-file-path: templates/pipeline/sam-pipeline.yaml

parameters: 
  Environment: dev
  SAMGitHubRepositoryName: manikandan-c-kf/sam-lambda
  SAMGitHubBranchName: main 
  CodeStarConnectionArn: arn:aws:codeconnections:us-east-1:961341513566:connection/cbd1908f-af4a-42bf-8464-9fc9e8ffc11d