template-file-path: templates/sam_pipeline.yaml

parameters: 
  Environment: dev
  SAMGitHubRepositoryName: manikandan-c-kf/sam-lambda
  SAMGitHubBranchName: main 
  CodeStarConnectionArn: arn:aws:codeconnections:us-east-1:767397811981:connection/1bfec851-eda0-4a60-bd54-31f73770815f  