template-file-path: templates/pipeline/sqs-lambda-sam-pipeline.yaml

parameters: 
  Environment: dev
  SQSLambdaSAMGitHubRepositoryName: manikandan-c-kf/mebwb-sqs-lambda-sam
  SQSLambdaSAMGitHubBranchName: main 
  CodeStarConnectionArn: arn:aws:codeconnections:us-east-1:961341513566:connection/cbd1908f-af4a-42bf-8464-9fc9e8ffc11d