AWSTemplateFormatVersion: "2010-09-09"
Description: SQS Queue for background jobs with Dead Letter Queue

Parameters:
  DLQName:
      Type: String
      Description: Name of the Dead Letter Queue
  MessageRetentionPeriod:
      Type: Number
      Description: Retention period for messages in the primary queue (in seconds)

Resources:
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref DLQName
      MessageRetentionPeriod: 1209600

  DeadLetterQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref DeadLetterQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "sqs:SendMessage"
            Resource: !GetAtt DeadLetterQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: "*"

Outputs:
  DeadLetterQueueArn:
    Description: ARN of the Dead Letter SQS Queue
    Value: !GetAtt DeadLetterQueue.Arn
    Export:
      Name: DeadLetterQueueArn

  DeadLetterQueueUrl:
    Description: URL of the Dead Letter SQS Queue
    Value: !Ref DeadLetterQueue
    Export:
      Name: !Sub "${AWS::StackName}-DeadLetterQueueUrl"