AWSTemplateFormatVersion: "2010-09-09"
Description: SQS Queue for background jobs with Dead Letter Queue

Parameters:
  QueueName:
    Type: String
    Description: Name of the primary SQS queue
  MessageRetentionPeriod:
      Type: Number
      Description: Retention period for messages in the primary queue (in seconds)
  MaxReceiveCount:
      Type: Number
      Description: Number of times a message can be received before moving to the DLQ

Resources:
  BackgroundJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName
      MessageRetentionPeriod: !Ref MessageRetentionPeriod
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: !Ref MaxReceiveCount

Outputs:
  BackgroundJobQueueArn:
    Description: ARN of the Background Job SQS Queue
    Value: !GetAtt BackgroundJobQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BackgroundJobQueueArn"

  BackgroundJobQueueUrl:
    Description: URL of the Background Job SQS Queue
    Value: !Ref BackgroundJobQueue
    Export:
      Name: !Sub "${AWS::StackName}-BackgroundJobQueueUrl"