AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Roles for Security Stack

Parameters:
  FrontendBucketName:
    Type: String
    Description: Name of the frontend S3 bucket

Resources:
  CloudFrontIDParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: CLOUDFRONT_ID
      Type: String
      Value: !ImportValue CloudFrontDistributionId
      Description: "CloudFront Distribution ID for the frontend application."

  S3BucketParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: S3_BUCKET
      Type: String
      Value: !Sub "${FrontendBucketName}"
      Description: "S3 bucket name for the frontend application."
