AWSTemplateFormatVersion: "2010-09-09"
Description: Security Groups for Application Resources

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, test, prod]
    Default: dev

Resources:
  ApplicationSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for application resources
      VpcId: !ImportValue VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !ImportValue LoadBalancerSecurityGroupId
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !ImportValue LoadBalancerSecurityGroupId

Outputs:
  SecurityGroupId:
    Description: ID of the created Security Group
    Value: !Ref ApplicationSecurityGroup
    Export:
      Name: "SecurityGroupId"
