AWSTemplateFormatVersion: "2010-09-09"
Description: Subnet Stack to create the public and private subnets along with their respective route tables

Parameters:
  Environment:
    Type: String
    Description: Environment to deploy (dev or staging or production).
  PublicSubnet1Cidr:
    Type: String
    Default: "172.29.0.0/20"
    Description: CIDR block for public subnet 1
  PublicSubnet2Cidr:
    Type: String
    Default: "172.29.16.0/20"
    Description: CIDR block for public subnet 2
  PublicSubnet3Cidr:
    Type: String
    Default: "172.29.32.0/20"
    Description: CIDR block for public subnet 3
  PublicSubnet4Cidr:
    Type: String
    Default: "172.29.48.0/20"
    Description: CIDR block for public subnet 4
  PublicSubnet5Cidr:
    Type: String
    Default: "172.29.64.0/20"
    Description: CIDR block for public subnet 5
  PublicSubnet6Cidr:
    Type: String
    Default: "172.29.80.0/20"
    Description: CIDR block for public subnet 6
  PrivateSubnet1Cidr:
    Type: String
    Default: "172.29.96.0/20"
    Description: CIDR block for private subnet 1
  PrivateSubnet2Cidr:
    Type: String
    Default: "172.29.112.0/20"
    Description: CIDR block for private subnet 2
  PrivateSubnet3Cidr:
    Type: String
    Default: "172.29.128.0/20"
    Description: CIDR block for private subnet 3
  PrivateSubnet4Cidr:
    Type: String
    Default: "172.29.144.0/20"
    Description: CIDR block for private subnet 4
  PrivateSubnet5Cidr:
    Type: String
    Default: "172.29.160.0/20"
    Description: CIDR block for private subnet 5
  PrivateSubnet6Cidr:
    Type: String
    Default: "172.29.176.0/20"
    Description: CIDR block for private subnet 6

Resources:
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue "VpcId"
      CidrBlock: !Ref PublicSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-public-1-${Environment}"

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue "VpcId"
      CidrBlock: !Ref PublicSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-public-2-${Environment}"

  PublicSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue "VpcId"
      CidrBlock: !Ref PublicSubnet3Cidr
      AvailabilityZone: !Select [2, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-public-3-${Environment}"

  PublicSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue "VpcId"
      CidrBlock: !Ref PublicSubnet4Cidr
      AvailabilityZone: !Select [3, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-public-4-${Environment}"

  PublicSubnet5:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue "VpcId"
      CidrBlock: !Ref PublicSubnet5Cidr
      AvailabilityZone: !Select [4, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-public-5-${Environment}"

  PublicSubnet6:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue "VpcId"
      CidrBlock: !Ref PublicSubnet6Cidr
      AvailabilityZone: !Select [5, !GetAZs ""]
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-public-6-${Environment}"

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue "VpcId"
      CidrBlock: !Ref PrivateSubnet1Cidr
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-private-1-${Environment}"

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue "VpcId"
      CidrBlock: !Ref PrivateSubnet2Cidr
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-private-2-${Environment}"

  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue "VpcId"
      CidrBlock: !Ref PrivateSubnet3Cidr
      AvailabilityZone: !Select [2, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-private-3-${Environment}"

  PrivateSubnet4:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue "VpcId"
      CidrBlock: !Ref PrivateSubnet4Cidr
      AvailabilityZone: !Select [3, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-private-4-${Environment}"

  PrivateSubnet5:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue "VpcId"
      CidrBlock: !Ref PrivateSubnet5Cidr
      AvailabilityZone: !Select [4, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-private-5-${Environment}"

  PrivateSubnet6:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue "VpcId"
      CidrBlock: !Ref PrivateSubnet6Cidr
      AvailabilityZone: !Select [5, !GetAZs ""]
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-private-6-${Environment}"

Outputs:
  PublicSubnetIds:
    Description: Comma-separated list of public subnet IDs
    Value: !Join 
      - ","
      - - !Ref PublicSubnet1
        - !Ref PublicSubnet2
        - !Ref PublicSubnet3
        - !Ref PublicSubnet4
        - !Ref PublicSubnet5
        - !Ref PublicSubnet6
    Export:
      Name: "PublicSubnetIds"

  PrivateSubnetIds:
    Description: Comma-separated list of private subnet IDs
    Value: !Join 
      - ","
      - - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2
        - !Ref PrivateSubnet3
        - !Ref PrivateSubnet4
        - !Ref PrivateSubnet5
        - !Ref PrivateSubnet6
    Export:
      Name: "PrivateSubnetIds"