AWSTemplateFormatVersion: "2010-09-09"
Description: Network Stack for VPC and Subnets

Parameters:
  Environment:
    Type: String
    Description: Environment to deploy (dev or staging or production).
  VpcCidr:
    Type: String
    Description: CIDR block for the VPC

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-vpc-${Environment}"

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-igw-${Environment}"

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

Outputs:
  VPCId:
    Description: The VPC ID
    Value: !Ref VPC
    Export:
      Name: "VpcId"

  InternetGatewayID:
    Description: ID of the internet gateway
    Value: !Ref InternetGateway
    Export:
      Name: "InternetGatewayId"

  AttachGatewayID:
    Description: ID of the attach gateway
    Value: !Ref AttachGateway
    Export:
      Name: "AttachGatewayId"