AWSTemplateFormatVersion: "2010-09-09"
Description: Network Stack for VPC and Subnets

Parameters:
  Environment:
    Type: String
    Description: Environment to deploy (dev or staging or production).
  VpcCidr:
    Type: String
    Description: CIDR block for the VPC

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-vpc-${Environment}"