AWSTemplateFormatVersion: "2010-09-09"
Description: WAF WebACL for ALB

Resources:
  WAFLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-WAFLoggingRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: wafv2.amazonaws.com
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: WAFLoggingPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !GetAtt WAFLogGroup.Arn
  IPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Addresses:
        - 192.0.2.0/24
        - 198.51.100.0/24
      IPAddressVersion: IPV4
      Scope: REGIONAL
      Name: !Sub "meb-${AWS::Region}-ipset"
      Description: "IPSet for blocking bad IPs"
      Tags:
        - Key: Name
          Value: !Sub "meb-${AWS::Region}-ipset"

  WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      DefaultAction:
        Allow: {}
      Scope: REGIONAL
      VisibilityConfig:
        CloudWatchMetricsEnabled: true
        MetricName: WebACLMetric
        SampledRequestsEnabled: true
      Name: !Sub "meb-${AWS::Region}-webacl"
      Rules:
      - Name: AWSManagedRulesBotControlRuleSet
        Priority: 1
        Statement:
          ManagedRuleGroupStatement:
            VendorName: AWS
            Name: AWSManagedRulesBotControlRuleSet
        OverrideAction:
          None: {}
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          MetricName: AWSManagedRulesBotControlRuleSet
          SampledRequestsEnabled: true

  WebACLAssociation:
    Type: AWS::WAFv2::WebACLAssociation
    Properties:
      ResourceArn: !ImportValue LoadBalancerArn
      WebACLArn: !GetAtt WebACL.Arn

  WAFLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/waf/${AWS::StackName}-logs"
      RetentionInDays: 30

Outputs:
  WebACLArn:
    Description: ARN of the WebACL
    Value: !Ref WebACL
    Export:
      Name: !Sub "${AWS::StackName}-WebACLArn"